baseURL = "https://matthewreesearch.com"
languageCode = "en-au"
title = "Matthew Rees"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  interests="Predator ecology; Invasive animals; Fire; Camera-trapping; Spatial capture-recapture, occupancy-detection, generalised additive and integrated population models."
  cv_name= "matthew-rees-CV.pdf"

[[params.affilation]]
  name = "University of Melbourne"
  position = "Applied Ecologist"
  contact = "matt.wayne.rees@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/matt-w-rees"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/matt_w_rees"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/matthew-w-rees/"


[[params.introduction.paragraph]]
  text=""" 
I'm a PhD candidate with the [QAECO](https://qaeco.com) lab at the University of Melbourne. I use quantitative methods to assist land managers with conservation problems centred around threatened and invasive species. 
Mammalian predators are inherently difficult to monitor and manage (also fairly interesting), and so, make up a large component of my research.
More broadly, my work tends to fall into three core themes: (1) estimating population dynamics and density, (2) modelling species interactions, and (3) integrating multiple types of data and models. 
I try to conduct this research at finescales and the individual-level where possible. 
My PhD thesis details the interactions between introduced foxes, feral cats and threatened prey, set against a backdrop of intensive fox control and prescribed fire.
   """


[[params.publications]]
  year="Peer-reviewed"
  
  [[params.publications.paper]]
    name = "Reptiles as food: predation of Australian reptiles by introduced red foxes compounds and complements predation by cats"
    authors = "A Stobo-Wilson... __MW Rees__..."
	  dest  = "*Wildlife Research*"
	  link = "https://www.publish.csiro.au/WR/justaccepted/WR20194"

		 [[params.publications.paper]]
    name = "Variation in feral cat density between two large adjacent islands in Australia’s monsoon tropics"
    authors = "H Davies, Tiwi Land Rangers, __MW Rees__, D Stokeld, A Miller, G Gillespie and B Murphy (2021)"
		dest  = "*Pacific Conservation Biology*"
	  link = "https://doi.org/10.1071/PC20088"
		
  [[params.publications.paper]]
		name = "Rapidly assessing cobenefits to advance threat‐management alliances"
		authors = "__MW Rees__, J Carwardine, A Reeson & J Firn (2020)"
		dest  = "*Conservation Biology*"
		link = "https://doi.org/10.1016/j.biocon.2019.108287"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Unexpectedly high densities of feral cats in a rugged temperate forest"
		authors = "__MW Rees__, JH Pascoe, BA Wintle, M Le Pla, EK Birnbaum & BA Hradsky (2019)"
		dest  = "*Biological Conservation*"
		link = "https://doi.org/10.1016/j.biocon.2019.108287"
		code_link = "https://github.com/matt-w-rees/feral-cat-otways-2017-SMR"
		blog_link = ""



[[params.publications]]
  year="In review"

  [[params.publications.paper]]
    name = "Genetic sampling and an activity index indicate contrasting lethal control outcomes"
    authors = "M Le Pla, EK Birnbaum, **MW Rees**, BA Hradsky, AR Weeks, A Van Rooyen and JH Pascoe"
  
  [[params.publications.paper]]
  name = "Sharing meals: predation on Australian mammals by the introduced European red fox compounds and complements predation by feral cats"
  authors = "A Stobo-Wilson... **MW Rees**..."

    
  [[params.publications.paper]]
  name = "Compounding and complementary carnivores: Australian bird species eaten by the introduced European red fox Vulpes vulpes and domestic cat Felis catus"
  authors = "A Stobo-Wilson... **MW Rees**..."

  [[params.publications.paper]]
  name = "Counting the bodies: the numbers of, and spatial variation in, Australian reptiles, birds and mammals killed by two introduced predators."
  authors = "A Stobo-Wilson... **MW Rees**..."
    
[[params.publications]]
  year="Reports"

  [[params.publications.paper]]
    name = "Monitoring and managing critical weight range mammals in the Indigenous protected areas of the world heritage Budj Bim cultural landscape"
    authors = "__MW Rees__"
    dest  = "*A report prepared for the Department of Environment, Land, Water and Planning*"
    link = ""
    code_link = ""
    blog_link = ""
    

